apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: filipelb777
  name: filipelb777
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector:
    app: filipe-finalapp # label of pods
  type: NodePort
status:
  loadBalancer: {}
